### ISSUE TITLE
sh scripts/visualize.sh error

### ISSUE THREAD

**Issue by zhangzscn** [swc-17/SparseDrive#60]
Hello author, the model has been trained and when I execute the visualization code, I get the following error. Could you please help me take a look? The model was trained on an 8-card machine, and the visualization is being run on a single-card machine. Additionally, I would like to save the visualization results. How can I do that?

root@dsw-106847-65cf99db47-fh68n:/mnt/workspace/zzs/SparseDrive# sh scripts/visualize.sh 
/usr/local/lib/python3.10/dist-packages/mmcv_full-1.7.2-py3.10-linux-x86_64.egg/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Use flash_attn_varlen_kvpacked_func
{'version': 'v1.0-trainval'}
Traceback (most recent call last):
  File "/mnt/workspace/zzs/SparseDrive/tools/visualization/visualize.py", line 114, in <module>
    main()
  File "/mnt/workspace/zzs/SparseDrive/tools/visualization/visualize.py", line 104, in main
    visualizer = Visualizer(args, plot_choices)
  File "/mnt/workspace/zzs/SparseDrive/tools/visualization/visualize.py", line 46, in __init__
    self.results = mmcv.load(args.result_path)
  File "/usr/local/lib/python3.10/dist-packages/mmcv_full-1.7.2-py3.10-linux-x86_64.egg/mmcv/fileio/io.py", line 68, in load
    obj = handler.load_from_fileobj(f, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv_full-1.7.2-py3.10-linux-x86_64.egg/mmcv/fileio/handlers/pickle_handler.py", line 12, in load_from_fileobj
    return pickle.load(file, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/storage.py", line 337, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1030, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1258, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1195, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 383, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 276, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 267, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by swc-17** [comment]
Hi, 这个问题是因为存入results.pkl的tensor如果是在gpu上，在pickle load的时候会重新放到对应device id的gpu上，所以想在单卡机器可视化，需要确保results.pkl的tensor放在cpu上。
