### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by davidpengiupui** [swc-17/SparseDrive#83]
感谢您的代码，但是我在尝试create data时遇到了以下的bug。请问要如何解决？
```14:30:17.489-08:00 | Traceback (most recent call last):
-- | --
14:30:17.489-08:00 | File "/code/tools/data_converter/nuscenes_converter.py", line 22, in <module>
14:30:17.489-08:00 | from projects.mmdet3d_plugin.datasets.map_utils.nuscmap_extractor import NuscMapExtractor
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/__init__.py", line 2, in <module>
14:30:17.489-08:00 | from .models import *
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/models/__init__.py", line 17, in <module>
14:30:17.489-08:00 | from .motion import *
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/models/motion/__init__.py", line 3, in <module>
14:30:17.489-08:00 | from .instance_queue import InstanceQueue
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/models/motion/instance_queue.py", line 10, in <module>
14:30:17.489-08:00 | from projects.mmdet3d_plugin.ops import feature_maps_format
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/ops/__init__.py", line 3, in <module>
14:30:17.489-08:00 | from .deformable_aggregation import DeformableAggregationFunction
14:30:17.489-08:00 | File "/code/projects/mmdet3d_plugin/ops/deformable_aggregation.py", line 4, in <module>
14:30:17.489-08:00 | from . import deformable_aggregation_ext
14:30:17.489-08:00 | ImportError: cannot import name 'deformable_aggregation_ext' from partially initialized module 'projects.mmdet3d_plugin.ops' (most likely due to a circular import) (/code/projects/mmdet3d_plugin/ops/__init__.py)```

**Comment by Jenny0420** [comment]
先编译算子
